### ISSUE TITLE
[Bug]: RangeError: Set maximum size exceeded

### ISSUE THREAD

**Issue by vulevukusej** [ThatOpen/engine_templates#7]
### What happened?

Loading a file on https://platform.thatopen.com/app and i receive the error below.

### Version

latest

### What browsers are you seeing the problem on?

Microsoft Edge

### Relevant log output

```shell
Uncaught (in promise) RangeError: Set maximum size exceeded
    at Set.add (<anonymous>)
    at aG.getAllGeometriesIDs (9249.a39bde93b4db5cf6.js:6:393264)
    at async aG.export (9249.a39bde93b4db5cf6.js:6:392019)
```

### Anything else?

Model has been sent to antonio@thatopen.com

**Comment by agviegas** [comment]
This should be solved in the latest version. Let us know otherwise!
